### PR TITLE
Added support query params in address bar

### PR DESCRIPTION
**Pull request by leonidlebedev**
Hi, Nataxo! How are you?

I saw your issue https://github.com/nataxo/url-query-comparison/issues/9 and decided to help you. My PR solve problem with sharing link, but it can be longer that you want.

<details>
  <summary><b>For example</b></summary>
  <code>/?first=https%3A%2F%2Fgithub.com%3Fa%3D1&second=https%3A%2F%2Fgithub.com%3Fa%3D2%26b%3D1&ignore=b</code>

</details>

### CODE REVIEW

**Comment by leonidlebedev** [comment]
I can't know what is problem. Could you help me, please?

**Comment by nataxo** [comment]
> I can't found out the problem. Could you help me, please?

I've looked at now build log and found out that build had failed because `describe is not defined`.
The problem lies in `pages/index.spec.js`. In `Next.js` every file in `pages` folder is treated as a webpack entry point.  Therefore, webpack attempts to build `index.spec.js` file and fails.
You should move page tests to `__spec__` folder in a project root. Please take a look at [next-with-jest](https://github.com/zeit/next.js/tree/canary/examples/with-jest).

<details><summary>build log</summary>

```
TaskID 2b28fda3-ee99-48c6-9490-8859cac63dce
@zeit/now-dcs-info: using https://dcs.now.systems as the upstream
running yarn for @now/build-utils@latest...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 40 new dependencies.
info Direct dependencies
└─ @now/build-utils@0.8.0
info All dependencies
├─ @now/build-utils@0.8.0
├─ async-retry@1.2.3
├─ async-sema@2.1.4
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ buffer-crc32@0.2.13
├─ concat-map@0.0.1
├─ core-util-is@1.0.2
├─ cross-spawn@6.0.5
├─ double-ended-queue@2.1.0-0
├─ end-of-stream@1.4.1
├─ from2@2.3.0
├─ fs-extra@7.0.0
├─ fs.realpath@1.0.0
├─ glob@7.1.3
├─ graceful-fs@4.2.0
├─ inflight@1.0.6
├─ into-stream@5.0.0
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ jsonfile@4.0.0
├─ minimatch@3.0.4
├─ multistream@2.1.1
├─ nice-try@1.0.5
├─ node-fetch@2.2.0
├─ p-is-promise@2.1.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ process-nextick-args@2.0.1
├─ readable-stream@2.3.6
├─ retry@0.12.0
├─ safe-buffer@5.1.2
├─ semver@6.1.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ string_decoder@1.1.1
├─ universalify@0.1.2
├─ util-deprecate@1.0.2
├─ which@1.3.1
└─ yazl@2.4.3
Done in 1.72s.
running yarn for @now/static-build...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 12 new dependencies.
info Direct dependencies
└─ @now/static-build@0.7.0
info All dependencies
├─ @now/static-build@0.7.0
├─ cross-spawn@6.0.5
├─ get-port@5.0.0
├─ isexe@2.0.0
├─ nice-try@1.0.5
├─ path-key@2.0.1
├─ promise-timeout@1.3.0
├─ semver@5.7.0
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ type-fest@0.3.1
└─ which@1.3.1
Done in 1.24s.
running builder.exports.build...
Downloading user files...
missing `engines` in `package.json`, using default range: 8.10.x
installing to /tmp/e3d2913

> core-js@2.6.9 postinstall /tmp/e3d2913/node_modules/core-js
> node scripts/postinstall || echo "ignore"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m

npm
 WARN e3d2913 No description
npm WARN e3d2913 No repository field.
npm WARN e3d2913 No license field.
npm 
WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN 
notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 934 packages in 9.34s
Running "now-build" script in "package.json"
running "npm run now-build"

> @ now-build /tmp/e3d2913
> next build && next export -o dist

Creating an optimized production build ...

> Using external babel configuration
> Location: "/tmp/e3d2913/.babelrc"
> Build error occurred
ReferenceError: describe is not defined
    at Module.y/TI (/tmp/e3d2913/.next/server/static/MeZu8-jZhF2M5nOuqr2r0/pages/index.test.js:1569:1)
    at __webpack_require__ (/tmp/e3d2913/.next/server/static/MeZu8-jZhF2M5nOuqr2r0/pages/index.test.js:23:31)
    at Object.1 (/tmp/e3d2913/.next/server/static/MeZu8-jZhF2M5nOuqr2r0/pages/index.test.js:99:18)
    at __webpack_require__ (/tmp/e3d2913/.next/server/static/MeZu8-jZhF2M5nOuqr2r0/pages/index.test.js:23:31)
    at /tmp/e3d2913/.next/server/static/MeZu8-jZhF2M5nOuqr2r0/pages/index.test.js:91:18
    at Object.<anonymous> (/tmp/e3d2913/.next/server/static/MeZu8-jZhF2M5nOuqr2r0/pages/index.test.js:94:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm
 ERR! code ELIFECYCLE
npm
 ERR! errno 1
npm
 ERR! @ now-build: `next build && next export -o dist`
npm ERR! Exit status 1
npm
 ERR! 
npm ERR!
 Failed at the @ now-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/.npm/_logs/2019-07-07T17_33_07_910Z-debug.log
Error: Exited with 1
    at ChildProcess.child.on (/tmp/255ad59a/.build-utils/node_modules/@now/build-utils/dist/fs/run-user-scripts.js:30:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

</details>

**Comment by leonidlebedev** [comment]
Filtered all `__spec__` folders in webpack config.

**Comment by nataxo** [comment]
Build fails again.
<details><summary>build logs<summary/>
```
TaskID 8407c55c-a07a-4d07-8567-a84f853a94b0
running yarn for @now/build-utils@latest...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 41 new dependencies.
info Direct dependencies
└─ @now/build-utils@0.8.8
info All dependencies
├─ @now/build-utils@0.8.8
├─ async-retry@1.2.3
├─ async-sema@2.1.4
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ buffer-crc32@0.2.13
├─ concat-map@0.0.1
├─ core-util-is@1.0.2
├─ cross-spawn@6.0.5
├─ double-ended-queue@2.1.0-0
├─ end-of-stream@1.4.1
├─ from2@2.3.0
├─ fs-extra@7.0.0
├─ fs.realpath@1.0.0
├─ glob@7.1.3
├─ graceful-fs@4.2.0
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ into-stream@5.0.0
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ jsonfile@4.0.0
├─ minimatch@3.0.4
├─ multistream@2.1.1
├─ nice-try@1.0.5
├─ node-fetch@2.2.0
├─ p-is-promise@2.1.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ process-nextick-args@2.0.1
├─ readable-stream@2.3.6
├─ retry@0.12.0
├─ safe-buffer@5.1.2
├─ semver@6.1.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ string_decoder@1.1.1
├─ universalify@0.1.2
├─ util-deprecate@1.0.2
├─ which@1.3.1
└─ yazl@2.4.3
Done in 1.54s.
running yarn for @now/static-build...
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 12 new dependencies.
info Direct dependencies
└─ @now/static-build@0.7.2
info All dependencies
├─ @now/static-build@0.7.2
├─ cross-spawn@6.0.5
├─ get-port@5.0.0
├─ isexe@2.0.0
├─ nice-try@1.0.5
├─ path-key@2.0.1
├─ promise-timeout@1.3.0
├─ semver@5.7.0
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ type-fest@0.3.1
└─ which@1.3.1
Done in 0.75s.
Downloading user files...
missing `engines` in `package.json`, using default range: 8.10.x
installing to /tmp/74ba629a

> core-js@2.6.9 postinstall /tmp/74ba629a/node_modules/core-js
> node scripts/postinstall || echo "ignore"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m


> core-js-pure@3.1.4 postinstall /tmp/74ba629a/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m

Creating an optimized production build ...

> Using external babel configuration
> Location: "/tmp/74ba629a/.babelrc"
Failed to compile.

./helpers/url.js
Module not found: Can't resolve '@babel/runtime-corejs2/core-js/object/entries' in '/tmp/74ba629a/helpers'

> Build error occurred
Error: > Build failed because of webpack errors
    at build (/tmp/74ba629a/node_modules/next/dist/build/index.js:6:847)
    at <anonymous>
npm
 ERR! code ELIFECYCLE
npm ERR!
 errno 1
npm
 ERR! @ now-build: `next build && next export -o dist`
npm 
ERR! Exit status 1
npm
 ERR! 
npm
 ERR! Failed at the @ now-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
     /tmp/.npm/_logs/2019-07-18T09_37_04_668Z-debug.log
Error: Exited with 1
    at ChildProcess.child.on (/tmp/1da8af7b/.build-utils/node_modules/@now/build-utils/dist/fs/run-user-scripts.js:30:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```
</details>

**Pull request merged**
